name: build

on: ['push', 'pull_request']

jobs:
  image:
    name: image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile