name: release

on:
  push:
    tags:
      - v*

jobs:
  image:
    name: image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/no-biden-or-trump

      - name: Push latest image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/uselections-2020:latest

      - name: Tag image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/no-biden-or-trump:latest ${{ secrets.DOCKER_USERNAME }}/no-biden-or-trump:${GITHUB_REF#refs/*/}

      - name: Push tagged image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/no-biden-or-trump:${GITHUB_REF#refs/*/}
